### ISSUE TITLE
Unexpected keyword 'const'

### ISSUE THREAD

**Issue by max107** [skpm/sketch-polyfill-fetch#8] opened 2017-11-16 17:43 UTC
How to reproduce
```
skpm create test
cd test
echo "export default function(context) { fetch('https://google.com'); }" > src/my-command.js
npm run start
```

Error trace:
```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode..
Plugin “my-command”, line 274:
» const SuperInit = (0, _runtime.SuperCall)(NSStringFromSelector("init"), [], { type: "@" });
```

Compiled code
```
// super when returnType is id and args are void
// id objc_msgSendSuper(struct objc_super *super, SEL op, void)

// HERE
const SuperInit = (0, _runtime.SuperCall)(NSStringFromSelector("init"), [], { type: "@" });
// HERE

// Returns a real ObjC class. No need to use new.
```

Info:
```
Mac 10.11.6
xcode 7.3.1
npm 5.3.0
skpm 1.0.8
```

**Comment by mathieudutour** [comment] 2017-11-16 18:24
yes it's a duplicate of #6 which has to do with https://github.com/darknoon/cocoascript-class/pull/1

**Closed as completed by mathieudutour** 2017-11-16 18:24 UTC
